### ISSUE TITLE
Griphon install Error

### ISSUE THREAD

**Issue by bykhoda** [vinivendra/Gryphon#128] opened 2023-04-13 14:18 UTC
error: the library 'GryphonLib' requires macos 10.13, but depends on the product 'SourceKittenFramework' which requires macos 12.0; consider changing the library 'GryphonLib' to require macos 12.0 or later, or the product 'SourceKittenFramework' to require macos 10.13 or earlier.

**Comment by vinivendra** [comment] 2023-04-13 14:21
Hey @bykhoda, I believe this is a duplicate of other issues we've been seeing, specifically the ones we're talking about on #127. I'll close it as a duplicate for now, but if you have any new information that might suggest this is a different issue, feel free to comment here again.

**Closed as completed by vinivendra** 2023-04-13 14:21 UTC
Labels: bug, duplicate
